import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AlertDialogProvider } from '@/components/ui/alert-dialog';
import { Navbar } from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const companyFont = Montserrat({ subsets: ['latin'], preload: true });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(companyFont.className, 'dark:bg-frx-blue-950 h-screen')}
      >
        <AlertDialogProvider>
          <div className="flex h-full relative items-start gap-8  p-8">
            <Navbar></Navbar>
            <div className="w-full h-full">{children}</div>
          </div>
        </AlertDialogProvider>
      </body>
    </html>
  );
}
