import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AlertDialogProvider } from '@/components/ui/alert-dialog';
import { Navbar } from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, 'dark:bg-frx-blue-950')}>
        <AlertDialogProvider>
          <div className="flex flex-col">
            <Navbar></Navbar>
            <div>{children}</div>
          </div>
        </AlertDialogProvider>
      </body>
    </html>
  );
}
